name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Unpack prebuilt libs, setup envs
      run: |
            inst=/opt/lib
            work=~/work/blender-termux/blender-termux
            tarball=libs.tar.gz
            mkdir -p $inst
            cd $inst
            tar xf $work/$tarball
            cd $work
    - name: Get and build libtiff, OpenImageIO 
      run: |
            link=https://gitlab.com/libtiff/libtiff/-/archive/master/libtiff-master.tar.gz
            tarball=$(basename "$link")
            tarname=$(echo "$tarball" | cut -d. -f1)
            inst=/opt/lib
            work=~/work/blender-termux/blender-termux
            NDK="$ANDROID_SDK_ROOT/ndk-bundle"
            setargs () { export cargs="-DCMAKE_PREFIX_PATH=$inst/$libname -DCMAKE_PREFIX_PATH=$inst/$libname -DCMAKE_INSTALL_PREFIX=$inst/$libname -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-24"; }
            wget -q $link
            tar xf $tarball
            echo $tarball
            echo $tarname
            libname=libtiff
            cd $tarname
            mkdir built
            cd built
            setargs
            cmake .. $cargs
            make
            make install
    - name: Get and build Blender
      run: |
            NDK="$ANDROID_SDK_ROOT/ndk-bundle"
            export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
            export TARGET=aarch64-linux-android
            export API=24
            export AR=$TOOLCHAIN/bin/llvm-ar
            export CC=$TOOLCHAIN/bin/$TARGET$API-clang
            export AS=$CC
            export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
            export LD=$TOOLCHAIN/bin/ld
            export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
            export STRIP=$TOOLCHAIN/bin/llvm-strip
            git clone https://git.blender.org/blender.git
            sed -i 's/-lgcc_s -lgcc/g' blender/build_files/build_environment/install_deps.sh
            ./blender/build_files/build_environment/install_deps.sh --no-confirm --build-all
