name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Unpack prebuilt libs, setup envs
      run: |
            export inst=/opt/lib
            export work=~/work/blender-termux/blender-termux
            tarball=libs.tar.gz
            export NDK="$ANDROID_SDK_ROOT/ndk-bundle"
            export cargs="-DCMAKE_PREFIX_PATH=$inst/$libname -DCMAKE_PREFIX_PATH=$inst/libname -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-24"
            mkdir -p $inst
            cd $inst
            tar xf $work/$tarball
            cd $work
    - name: Get and build libtiff, OpenImageIO 
      run: |
            link=https://gitlab.com/libtiff/libtiff/-/archive/master/libtiff-master.tar.gz
            export tarball=$(basename "$link")
            export tarname=$(echo "$tarball" | cut -d. -f1)
            wget -q $link
            tar xf $tarball
            echo $tarball
            echo $tarname
            export libname=libtiff
            cd $tarname
            mkdir built
            cd built
            cmake $cargs ..
            make
            make install
